imports:
  - { resource: parameters.yml }

services:
  ## CONTROLLERS ##
  home_controller:
    class: 'Controller\HomeController'
    arguments:
      - '@twig'
      - '@link_service' 

  ## SERVICES ##
  link_service:
    class: 'Service\Link'
    arguments:
      - '@database'
      - '@tweet_service'

  tweet_service:
    class: 'Service\Tweet'
    arguments:
      - '@database'

  ## SUPPORTING CODE
  twig_loader:
    class: 'Twig_Loader_Filesystem'
    arguments:
      - '%template_location%'

  twig:
    class: 'Twig_Environment'
    arguments:
      - '@twig_loader'
      - '%twig.config%'
    calls:
      - ['addExtension', ['@twig_debug']]

  twig_debug:
    class: 'Twig_Extension_Debug'


  database:
    class: 'mysqli'
    arguments:
      - '%dbhost%'
      - '%dbuser%'
      - '%dbpassword%'
      - '%database%'

